reload("user.plugins")
reload("user.colorscheme")
reload("user.options")
reload("user.keymaps")
reload("user.lsp")
reload("user.kind")
reload("user.cmp")
reload("user.banners")
reload("user.which-key")
reload("user.code_runner")
reload("user.boole")
reload("user.hlsearch")
reload("user.lastplace")
reload("user.betterEscape")
reload("user.oil")
-- reload("user.lsp-sig")

require("luasnip").filetype_extend("javascript", { "javascriptreact" })
require("luasnip").filetype_extend("typescriptreact", { "html" })
require("luasnip").filetype_extend("javascript", { "html" })
require("luasnip").filetype_extend("typescriptreact", { "javascript" })
